services:
  - type: web
    name: memoirs
    runtime: python
    plan: starter
    region: singapore
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application
    disk:
      name: memoirs-media
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: ALLOW_PUBLIC_REGISTRATION
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: MEDIA_ROOT
        value: /var/data/media
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
